export const ITEM_ADDED = 'ITEM_ADDED';
export const ITEM_REMOVED = 'ITEM_REMOVED';
export const ITEM_PRICE_UPDATE = 'ITEM_PRICE_UPDATE';
export const ITEM_QUANTITY_UPDATE = 'ITEM_QUANTITY_UPDATE';

export const TIP_PERCENTAGE_UPDATED = 'TIP_PERCENTAGE_UPDATED';
